---
title: "Mapping Final Submission"
author: "Anna Cook"
date: "10/30/2020"
output: pdf_document
---
# GGplot2 Maps
```{r, echo=FALSE}
library(maps)
library(tmap)
library(hurricaneexposuredata)
library(tidyverse)
library(drat)
library(magrittr)
library(sf)
```


```{r, echo=FALSE}
##read data
addRepo("geanders")
data("hurr_tracks")
data("rain")
county <- map_data("county")   
data(county.fips)
```


```{r, echo=FALSE}
##separate polygon column into state and county columns
fips_data <- county.fips %>%
  as_tibble %>% 
  separate(polyname, c("region", "subregion"), "," )

##merge county data with fips data
all_data <- map_data("county") %>% 
  left_join(fips_data)
```


```{r, echo=FALSE}
##map only the states needed
mp_states <- c("texas", "oklahoma", "kansas",
               "iowa", "missouri", "arkansas", "louisiana",
               "alabama", "mississippi", "georgia", "florida",
               "tennessee","kentucky", "indiana", 
               "wisconsin", "michigan", "illinois",
               "ohio", "west virginia", "pennsylvania",
               "south carolina", "north carolina", 
               "virginia", "delaware", "maryland",
               "new jersey", "district of columbia", 
               "new york", "connecticut", "rhode island",
               "massachusetts", "vermont", "new hampshire",
               "maine")

state_data <- map_data('state', region = mp_states)

all_data  %<>% filter(region %in% mp_states)
```

## Floyd-1999
```{r, echo=FALSE}
#filter data for Floyd-1999
floyd_track <- hurr_tracks %>% filter(storm_id=="Floyd-1999")
floyd_rain <- rain %>% filter(storm_id=="Floyd-1999")

# organize rain data
fr <- floyd_rain %>% group_by(fips) %>% summarise(rain = sum(precip))
```


```{r, echo=FALSE}
# code added from group review
fr2 <- as.data.frame(fr)
for (i in 1:dim(fr2)[1]){
  fr2$rain[i] <- fr2$rain[i]%/%25
}

# create intervals for rain scale
fr2$rain <- ordered(fr2$rain,labels = c("[0,25]","(25,50]","(50,75]","(75,100]","(100,125]","(125,150]","(150,175]","(175,200]","(200,220]"))
```


```{r, echo=FALSE}
# join rain data with all data
fr2$fips <- as.numeric(fr2$fips)
aa <- left_join(all_data, fr2)
aa <- na.omit(aa)
```


```{r, echo=FALSE}
##Floyd-1999 Map (ggplot2)
ggplot() +
  geom_polygon(data=aa, aes(x=long, y=lat, group=group, fill=rain), color="black", size=0.05) +
  scale_fill_brewer(palette = "Blues", name = "Rainfall(mm)")+
  labs(title = "Floyd-1999")+
  theme(plot.title = element_text(face = "bold", size =14, hjust = 0.5)) +
  theme(legend.position = "right") +
  geom_path(data=floyd_track, aes(x=longitude, y=latitude), color="red", size=0.5)
```

## Allison-2001
```{r, echo=FALSE}
#filter data for Allison-2001
allison_track <- hurr_tracks %>% filter(storm_id=="Allison-2001")
allison_rain <- rain %>% filter(storm_id=="Allison-2001")

# organize rain data
ar <- allison_rain %>% group_by(fips) %>% summarise(rain = sum(precip))
```


```{r, echo=FALSE}
# code added from group review
ar2 <- as.data.frame(ar)
for (i in 1:dim(ar2)[1]){
  if (ar2$rain[i] < 175){
    ar2$rain[i] <- 0
  }
  else {ar2$rain[i] <- 1}
}

# create labels for rain exposure
ar2$rain <- ordered(ar2$rain, labels = c("Unexposed","Exposed"))

# join rain data with all data
ar2$fips <- as.numeric(ar2$fips)
bb <- left_join(all_data, ar2)
bb <- na.omit(bb)
```


```{r, echo=FALSE}
# Allison map (ggplot2)
ggplot() +
  geom_polygon(data=bb, aes(x=long, y=lat, group=group, fill=rain), color="black", size=0.05) +
  scale_fill_brewer(palette = "Blues", name = "Rainfall > 175mm")+
  labs(title = "Allison-2001")+
  theme(plot.title = element_text(face = "bold", size =14, hjust = 0.5)) +
  theme(legend.position = "right") +
  geom_path(data=allison_track, aes(x=longitude, y=latitude), color="red", size=0.5)
```

# Tmap Maps
```{r, echo=FALSE}
# create shape file for counties
tcounties <- st_as_sf(maps::map('county',mp_states,plot=F,fill=T))

# test map
tm_shape(tcounties) + tm_polygons()
```

## Floyd-1999
```{r, echo=FALSE}
# join datasets together with the shape file
t_rain <- left_join(fr2, county.fips)
t_rain <- rename(t_rain, ID = polyname)
t_all <- left_join(tcounties, t_rain)

# the following line of code did not run, and I'm not sure why
#tm_shape(t_all) + tm_polygons(col=rain, palette = "Blues")
```

## Allison-2001
```{r, echo=FALSE}
# join datasets together with the shape file
a_rain <- left_join(ar2, county.fips)
a_rain <- rename(a_rain, ID = polyname)
a_all <- left_join(tcounties, a_rain)

# the following line of code didn't run and I'm not sure why
#tm_shape(a_all) + tm_polygons(col=rain, palette = "Blues")
```


